# Generated by Django 4.0 on 2024-12-01 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre_de_usuario', models.CharField(max_length=150, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('edad', models.PositiveIntegerField(default=0)),
                ('es_superusuario', models.BooleanField(default=False)),
                ('es_personal', models.BooleanField(default=False)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
