# Generated by Django 4.0 on 2024-11-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_de_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='usuario', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
